// Package blueprint provides types and functions for parsing Aiken's plutus.json
// (CIP-0057 Plutus Blueprint) and generating Go code for type-safe datums,
// redeemers, and validators.
package blueprint

import (
	"encoding/json"
	"fmt"
	"os"
)

// Blueprint represents a CIP-0057 Plutus Blueprint generated by Aiken.
type Blueprint struct {
	Preamble    Preamble           `json:"preamble"`
	Validators  []Validator        `json:"validators"`
	Definitions map[string]*Schema `json:"definitions"`
}

// Preamble contains metadata about the Aiken project.
type Preamble struct {
	Title         string   `json:"title"`
	Description   string   `json:"description"`
	Version       string   `json:"version"`
	PlutusVersion string   `json:"plutusVersion"`
	Compiler      Compiler `json:"compiler"`
	License       string   `json:"license"`
}

// Compiler contains information about the Aiken compiler version.
type Compiler struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// Validator represents a compiled Plutus validator/script.
type Validator struct {
	Title        string      `json:"title"`
	Datum        *Parameter  `json:"datum,omitempty"`
	Redeemer     Parameter   `json:"redeemer"`
	Parameters   []Parameter `json:"parameters,omitempty"`
	CompiledCode string      `json:"compiledCode"`
	Hash         string      `json:"hash"`
}

// Parameter represents a datum, redeemer, or script parameter.
type Parameter struct {
	Title  string `json:"title,omitempty"`
	Schema Schema `json:"schema"`
}

// LoadBlueprint reads and parses a plutus.json file.
func LoadBlueprint(path string) (*Blueprint, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading blueprint file: %w", err)
	}

	var bp Blueprint
	if err := json.Unmarshal(data, &bp); err != nil {
		return nil, fmt.Errorf("parsing blueprint JSON: %w", err)
	}

	return &bp, nil
}

